global:
  scrape_interval: 5s # 5초마다 데이터 수집

scrape_configs:
  - job_name: 'mini-ssem'
    metrics_path: '/actuator/prometheus' # Spring Boot Prometheus 엔드포인트
    static_configs:
      - targets: ['localhost:8080'] # Spring Boot 앱 주소